name: download

on: workflow_dispatch
#on: [push, pull_request]

jobs:
  windows_Tset:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4

    # 下载    
    - name: Down
      run: |
        #ls     #Directory: D:\a\TestGithubActions\TestGithubActions(即仓库目录)
        
        cd ..   #Directory: D:\a\TestGithubActions
        
        mkdir -p download
        
        curl -L -o Qt5.15.14-Windows-x86_64-VS2017-15.9.63-20240613.7z https://sourceforge.net/projects/fsu0413-qtbuilds/files/Qt5.15/Windows-x86_64/MSVC/Qt5.15.14-Windows-x86_64-VS2017-15.9.63-20240613.7z
        curl -L -o Qt5.15.14-Windows-x86_64-VS2019-16.11.37-20240613.7z https://sourceforge.net/projects/fsu0413-qtbuilds/files/Qt5.15/Windows-x86_64/MSVC/Qt5.15.14-Windows-x86_64-VS2019-16.11.37-20240613.7z
        curl -L -o Qt5.15.14-Windows-x86_64-VS2022-17.10.3-20240622.7z https://sourceforge.net/projects/fsu0413-qtbuilds/files/Qt5.15/Windows-x86_64/MSVC/Qt5.15.14-Windows-x86_64-VS2022-17.10.3-20240622.7z
    
    # 打包
    - name: Package binaries
      run: |
        #ls     #Directory: D:\a\TestGithubActions\TestGithubActions(即库存目录)
        7z a download.7z ../download -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: download
        path: download.7z