name: Test

#on: workflow_dispatch
on: [push, pull_request]

jobs:
  windows_Tset:
    runs-on: windows-latest

    steps:
    - name: Build Qt
      run: |
        #ls #Directory: D:\a\TestGithubActions\TestGithubActions即库存目录
        cd ..
        mkdir -p Qt
        ls