name: Test

#on: workflow_dispatch
on: [push, pull_request]

jobs:
  windows_Tset:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Build Qt
      run: |
      cd ..
      mkdir Qt
      cd Qt
      mkdir 6.8.2
      mkdir 6.8.2-static

    - name: Package binaries
      run: |
        # 打包
        7z a Tset.zip ..\Qt\6.8.2-static
    # 上传
    - uses: actions/upload-artifact@v4.5.0
      with:
        name: Tset
        path: Tset.zip