name: Test

#on: workflow_dispatch
on: [push, pull_request]

jobs:
  windows_Tset:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 构建 Qt    
    - name: Build Qt
      run: |
        #设置powershell变量，设置Qt版本
        $QT_VERSION=6.8.3 
      
        #ls     #Directory: D:\a\TestGithubActions\TestGithubActions(即库存目录)
        
        cd ..   #Directory: D:\a\TestGithubActions
        mkdir -p Qt
        
        cd Qt   #Directory: D:\a\TestGithubActions\Qt
        mkdir -p $QT_VERSION
        mkdir -p $QT_VERSION-static
        
        cd ..   #Directory: D:\a\TestGithubActions
        Copy-Item -Path ./TestGithubActions/qt.conf -Destination ./Qt/6.8.2-static/
    
    # 打包
    - name: Package binaries
      run: |
        #ls     #Directory: D:\a\TestGithubActions\TestGithubActions(即库存目录)
        7z a Tset.zip ../Qt
    
    # 上传
    - uses: actions/upload-artifact@v4.5.0
      with:
        name: Tset
        path: Tset.zip