name: Test2

#on: workflow_dispatch
on: [push, pull_request]

env:
  QT_VERSION: 6.8.2
  FILE_NAME: Tset2

jobs:
  windows_Tset:
    runs-on: windows-latest

    steps:
    # 检出本仓库
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # 构建 Qt    
    - name: Build Qt
      run: |
        cmd.exe /c "call `"D:\a\TestGithubActions\TestGithubActions\Test2.cmd`""

    # 打包
    - name: Package binaries
      run: |
        #ls     #Directory: D:\a\TestGithubActions\TestGithubActions(即库存目录)
        7z a ${{ env.FILE_NAME }}.7z ../Qt/${{ env.QT_VERSION }}-static -mx=9

    # 上传
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FILE_NAME }}
        path: ${{ env.FILE_NAME }}.7z