name: Test

#on: workflow_dispatch
on: [push, pull_request]

jobs:
  windows_Tset:
    runs-on: windows-latest

    steps:
    - name: Build Qt
      run: |
        #ls     #Directory: D:\a\TestGithubActions\TestGithubActions即库存目录
        
        cd ..   #Directory: D:\a\TestGithubActions
        mkdir -p Qt
        
        cd Qt   #Directory: D:\a\TestGithubActions\Qt
        mkdir -p 6.8.2
        mkdir -p 6.8.2-static
        Copy-Item -Path ../TestGithubActions/qt.conf -Destination ./6.8.2-static/
        
        cd 6.8.2-static
        ls