name: Test

#on: workflow_dispatch
on: [push, pull_request]

jobs:
  windows_Tset:
    runs-on: windows-latest

    steps:
    - name: Build Qt
      run: |
        #ls      #Directory: D:\a\TestGithubActions\TestGithubActions(即库存目录)
        #cd ..   #Directory: D:\a\TestGithubActions
        #以下均在库存目录D:\a\TestGithubActions\TestGithubActions下操作
        mkdir -p Qt
        
        cd Qt   #Directory: D:\a\TestGithubActions\Qt
        mkdir -p 6.8.2
        mkdir -p 6.8.2-static
        cd..
        
        Copy-Item -Path ./qt.conf -Destination ./Qt/6.8.2-static/
        
        cd Qt
        cd 6.8.2-static
        ls