name: Test

#on: workflow_dispatch
on: [push, pull_request]

jobs:
  windows_Tset:
    runs-on: windows-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Build Qt
      run: |
        #ls #Directory: D:\a\TestGithubActions\TestGithubActions即库存目录
        cd ..
        mk -p Qt
        ls